type Channel {
  country: String
  customUrl: String
  defaultLanguage: String
  description: String
  publishedAt: String
  thumbnailUrl: String
  title: String
  uploadsPlaylist: String
}

type Comment {
  authorChannelId: String
  authorChannelUrl: String
  authorDisplayName: String
  authorProfileImageUrl: String
  channelId: String
  likeCount: String
  moderationStatus: String
  parentId: String
  publishedAt: String
  textDisplay: String
  updatedAt: String
  viewerRating: String
}

type PlaylistItem {
  channelId: String
  channelTitle: String
  description: String
  playlistId: String
  position: String
  publishedAt: String
  thumbnailUrl: String
  title: String
  videoId: String
  videoOwnerChannelId: String
  videoOwnerChannelTitle: String
}

type PlaylistItemsResponse {
  items: [PlaylistItem!]
  nextPageToken: String
  prevPageToken: String
}

type Query {
  channel(channelId: String!): Channel
  comments(videoId: String!): [Comment!]
  playlist(pageToken: String, playlistId: String!): PlaylistItemsResponse
  search(pageToken: String, q: String!): SearchResponse
  video(id: String!): Video
}

type SearchResponse {
  items: [SearchResult!]
  nextPageToken: String
  prevPageToken: String
}

type SearchResult {
  channelId: String
  channelTitle: String
  description: String
  liveBroadcastContent: String
  playlistId: String
  publishedAt: String
  thumbnailUrl: String
  title: String
  videoId: String
}

type Video {
  categoryId: String
  channelId: String
  channelTitle: String
  commentCount: String
  defaultAudioLanguage: String
  defaultLanguage: String
  description: String
  dislikeCount: String
  favoriteCount: String
  likeCount: String
  liveBroadcastContent: String
  publishedAt: String
  tags: [String!]
  thumbnailUrl: String
  title: String
  viewCount: String
}

type VideoResponse {
  items: [Video!]
  nextPageToken: String
  prevPageToken: String
}